### ISSUE TITLE
installation with npm and capacitor 5 support

### ISSUE THREAD

**Issue by metalllus** [Captive-Studio/capacitor-plugins#503]
Hello, sorry for a newbie question but how do I install this if I am using NPM in my project not yarn? And is Capacitor 5 supported?

**Comment by jpolo** [comment]
Yes this package is compatible with capacitor v5. For npm, just run npm install --save-dev @captive/capacitor-facebook-analytics.

**Comment by fikret8figures** [comment]
@jpolo, what about Capacitor versions 6 and 7? I'm using 6, but planning to move to 7 soon. Is your recommendation still relevant? 

`npm install --save-dev @captive/capacitor-facebook-analytics`
